apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "open-ondemand.fullname" . }}-nfs-pv
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.volume.storageClass }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: {{ .Values.advanced.fileSharing.mountPoint | quote }}