apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "open-ondemand.fullname" . }}-nfs-pvc
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.volume.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.advanced.fileSharing.nfs_volume_size }}